preview: "@sam"
label: Demo
status: wip
notes: |
  A card can have a horizontal header, a vertical header, or no header.

  **Horizontal Header**
  May have a title and an icon, one or two buttons, or an action item. Card headers with actions should have an action modifier "sds-card__header--action"

  ***Lists***
  Cards with horizontal headers can also be lists. Just add list modifier to top level sds-card element(*```sds-card sds-card--list```*)

  **No Header**
  508: card must have `aria-labelledby` attribute with a corresponding header outside of card
  ___
  **Variables:**
  - color (*optional*): option of base, accent-cool, accent-warm, or feature
  - title:
  - modifiers: [vertical and list]
  - header: *(false if no header)*
    - style: option of left, stacked, center, action or flex
    - link: url
    - icon: @icon
    - buttons: [@button]
    - action: Boolean
  - body
    - grid: Boolean to use grid
    - content: [component, text, and/or html]
      - component
        - component: component *(ie: list)*
        - context (*optional*): context for nested component
        - col (*optional*): column width if body is a grid **default is grid-col**
        - extend (*optional*): Boolean to extend component's default content
      - text
        - text: string
        - col (*optional*): column width if body is a grid **default is grid-col**
      - html
        - html: ```html element```
        - col (*optional*): column width if body is a grid **default is grid-col**
display:
  text-align: center
meta:
  colors:
    - title: Plain
    - modifier: base
      title: Base
    - modifier: accent-cool
      title: Accent Cool
    - modifier: accent-warm
      title: Accent Warm
    - modifier: feature
      title: Feature (Secondary)
context:
  card:
    color: null
    title: Contract Opportunities
    subtitle: Lorem Ipsum
    header:
      style: left
    body:
      content:
        - text: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae.
variants:
  - name: bordered
    label: Bordered No Shadow
    context:
      card:
        classes:
          - shadow-none
  - name: shadowed
    label: Shadowed No Border
    context:
      card:
        classes:
          - border-width-0
  - name: no shadow
    label: No Shadow or Border
    context:
      card:
        classes:
          - shadow-none
          - border-width-0
  - name: no header
    label: No Header
    meta:
      colors:
    context:
      card:
        header: false
  - name: link header
    label: Link Header
    notes: Header can be a link.
    context:
      card:
        header:
          link: " "
  - name: header icon left
    label: Header Icon Left
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x fa-fw
  - name: header icon stacked
    label: Header Icon Stacked
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x
          style: stacked
  - name: header icon centered
    label: Header Icon Centered
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x fa-fw
          style: center
  - name: header button
    label: Header with One Button
    context:
      card:
        header:
          buttons:
            - modifiers:
              - outline
          style: flex
  - name: header buttons
    label: Header with Two Buttons
    context:
      card:
        header:
          buttons:
            - modifiers:
              - outline
            - modifiers:
              - outline
          style: flex
  - name: header action
    label: Header with Action Button
    context:
      card:
        header:
          action: true
          style: action
  - name: vertical
    label: Vertical Header
    context:
      card:
        modifiers:
          - vertical
        header:
          icon:
            icon: question-circle
            classes: fa-2x
  - name: collapsible
    label: Collapsible Card
    context: 
      card: 
        modifiers:
          - collapsible
        body:
          type:
            - collapsed
      
  - name: list
    label: List
    context:
      card:
        modifiers:
          - list
        body:
          content:
            - component: list
              context:
                modifiers:
                - bordered
                - unstyled
              extend: true
