label: Tags
status: wip
preview: "@sam-grid"
variants:
  - name: default
    label: Info
    context:
      label:
        classes: "usa-tag"

  - name: chip
    label: Chip
    context:
      label:
        classes: "sds-tag sds-tag--chip"

  - name: status
    label: Status
    context:
      label:
        classes: "sds-tag sds-tag--status"

  - name: outline-sam
    label: Outlined SAM
    context:
      label:
        classes: "sds-tag sds-tag--outline"

  - name: outline
    label: Outlined Extended
    context:
      label:
        classes: "sds-tag sds-tag--outline"
