label: Collection
status: wip
preview: "@sam-grid"
variants:
  - name: default
    label: Default
    context:
      label:
        classes: "collection"
  - name: media
    label: Media
    context:
      label:
        classes: "collection--media"
  - name: calendar
    label: Calendar
    context:
      label:
        classes: "collection--calendar"
  - name: condensed
    label: Condensed
    context:
      label:
        classes: "collection--condensed"
